[env]
mode = "local" # local | test | prod

[serve]
port = 8089
# stoptime = "6000ms"  # 服务收到关闭请求后, 等待多少时间等现有业务收尾
pprofbearer = "81bea8c8eaad642"

[log]
level = "DEBUG" # DEBUG | INFO | WARN | ERROR

[mysql]
# docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=123456 -p 3306:3306 mysql
main = "mysql -uroot -p123456 -hlocalhost -P3306 resource_ai_drama"
